### PR TITLE
Fixed for linux.

### LINKED ISSUE #2: `#!/usr/bin/env node --harmony` doesn't work on linux
I do my build with circleci and this doesn't [appear to be allowed on linux](https://bbs.archlinux.org/viewtopic.php?id=168479).

I might have a quick crack at fixing in a sec.

### PR DESCRIPTION
**Pull request by richardgill**
fixes #2 

See https://bbs.archlinux.org/viewtopic.php?id=168479

### CODE REVIEW

**Comment by joshuapinter** [comment]
Hey @richardgill, thanks for bringing this up!

Can you try using `#!/usr/bin/node --harmony` at the top instead and let me know if it works?

Just reading up on this here: http://stackoverflow.com/questions/24548733/how-to-make-a-nodejs-file-executable-with-harmony-option

Thanks!

**Comment by richardgill** [comment]
That doesn't work on osx :(. The first solution isn't any good it seems to lose args to your command.

**Comment by joshuapinter** [comment]
Hmm. You're right. 

When I use your EOF method I get an error on Mac. Does it work for you doing this method on Mac?

**Comment by joshuapinter** [comment]
I'm a little surprised there's not a good workaround for this.

I tried it without using the `--harmony` flag and it builds and deploys just fine. I don't think I'm using any Harmony sugar in there. 

Can you try without the `--harmony` flag as well on both your Mac and Circle CI and let me know if that works?

Many Thanks!

**Comment by richardgill** [comment]
```
if (program.target && !permittedValues.includes(program.target)) {
                                         ^

TypeError: permittedValues.includes is not a function
    at checkOptionValues (/Users/richard/Workspace/change-please-app/node_modules/apphubdeploy/AppHubDeploy.js:60:42)
    at Object.<anonymous> (/Users/richard/Workspace/change-please-app/node_modules/apphubdeploy/AppHubDeploy.js:29:1)
    at Module._compile (module.js:399:26)
    at Object.Module._extensions..js (module.js:406:10)
    at Module.load (module.js:345:32)
    at Function.Module._load (module.js:302:12)
    at Function.Module.runMain (module.js:431:10)
    at startup (node.js:141:18)
    at node.js:977:3
```

**Comment by joshuapinter** [comment]
Ugh... okay. Thanks for trying that.

Did you ever try the EOF method on your Mac?

**Comment by richardgill** [comment]
Yup gave an error for me too. Maybe we should split this into two files?

**Comment by joshuapinter** [comment]
You mean having one file launch the other one with the `--harmony` flag set? 

Kinda like this: http://stackoverflow.com/a/22731082/293280

**Comment by richardgill** [comment]
Good idea! That seems to have done the trick 👍. Tested on osx and linux.

I've done a lot of silly commits, so whenever you merge in Github please hit squash!

**Comment by joshuapinter** [comment]
Don't ask me how it works but you're right, it does! :)

I'll go ahead and merge it in now and publish a new version for your package.json.

**Comment by richardgill** [comment]
Thanks 😄

**Comment by joshuapinter** [comment]
Thank you! :+1:

**Comment by joshuapinter** [comment]
Okay, new npm package version is 0.0.7. Thanks again.

**Pull request merged**
